### ISSUE TITLE
Help wanted with packages unikraft images

### ISSUE THREAD

**Issue by alanpjohn** [nubificus/bima#34]
I was attempting to package some of my unikraft applications with Bima to run with [urunc](https://github.com/nubificus/urunc/tree/main), but I am struggling to understand how to write my ContainerFile to package them with Bima.

Could you please guide me on some examples of ContainerFiles for some of the examples in the [Unikraft Catalog](https://github.com/unikraft/catalog), such as
1. [HTTP Application in C++](https://github.com/unikraft/catalog/tree/main/examples/http-cpp)
2. [Python 3.10 Flask HTTP Application](https://github.com/unikraft/catalog/tree/main/examples/http-python3.10-flask3.0)

Thanks in Advance!!

**Comment by cmainas** [comment]
Hello @alanpjohn , thank you for trying out our tool.

If you simply want to get Unikraft catalog images and run them in `urunc` we would recommend to use [pun](https://github.com/nubificus/pun). We built this tool for simply obtaining unikraft images from unikraft's registry and adding the necessary annotations for `urunc`. 

If you want to build your own unikernel image with unikraft and then package it for `urunc` you can still use `pun` or check [bima's README](https://github.com/nubificus/bima/blob/main/README.md).

In both cases you will need to specify the annotations for `urunc`. Therefore let me go over the available annotations:
Required:
- `com.urunc.unikernel.unikernelType`: The type of the unikernel (can be rumprun, unikraft, etc)
- `com.urunc.unikernel.hypervisor`: The desired hypervisor to run the unikernel (e.g. qemu, firecracker, hvt)
- `com.urunc.unikernel.binary`: The path to the unikernel binary inside the container image
- `com.urunc.unikernel.cmdline`: The cmdline of the application that will run inside the unikernel.

Except of the above, `urunc` accepts the following optional annotations:
- `com.urunc.unikernel.unikernelVersion`: The version of the framework used to build the unikernel (e.g. 0.17.0). If you use newer unikraft versions you should definitely use this annotation.
- `com.urunc.unikernel.initrd`: The path to the initrd of the unikernel inside the container image.
- `com.urunc.unikernel.block`: The path to a block image, in order to attach to the unikernel
- `com.urunc.unikernel.blkMntPoint`: The mount point of the block image inside the unikernel

Therefore for the C++ HTTP application the annotations could be:
 ```
LABEL com.urunc.unikernel.binary="path/to/unikernel/binary"
LABEL "com.urunc.unikernel.cmdline"="run /http_server" ## obtained from the Kraftfile,
LABEL "com.urunc.unikernel.unikernelType"="unikraft"
LABEL "com.urunc.unikernel.hypervisor"="qemu"
 ```
 
 For the cmdline you may omit `run` as soon as [this PR](https://github.com/nubificus/urunc/pull/72) get merged in `urunc`. 
 
 Depending on either you build from scratch the unikraft image or not you might need to also use the `COPY` command as specified in [bima's README](https://github.com/nubificus/bima/blob/main/README.md).
 
 EDIT: Changed last required annotation from `version` -> `unikernelVersion`

**Comment by alanpjohn** [comment]
Hi @cmainas, thank you for responding.

I built the `native/http-c` example for the unikraft demo without using pun by following some instructions on https://github.com/nubificus/urunc/issues/52 but most of the applications that I have built on unikraft run similarly to how `examples/http-cpp` `examples/http-go` `examples/http-python-3.12-flask`, I am struggling a bit in packaging these with `pun`. For `examples/http-cpp`, after building the initrd, I try to package with pun using the following ContainerFile based on instructions [here](https://github.com/nubificus/pun/tree/main?tab=readme-ov-file#packaging-a-unikraft-unikernel-with-pun-with-buildctl)
```Dockerfile
FROM unikraft.org/base:latest

COPY ./.unikraft/build/initramfs-x86_64.cpio /unikraft/initrd
LABEL "com.urunc.unikernel.binary"="/unikraft/bin/kernel"
LABEL "com.urunc.unikernel.cmdline"="run http_server"
LABEL "com.urunc.unikernel.unikernelType"="unikraft"
LABEL "com.urunc.unikernel.hypervisor"="qemu"

LABEL "com.urunc.unikernel.initrd"="/unikraft/initrd"
```

And then run pun to get the following error
```bash
pun -f Containerfile | sudo buildctl build --local context=${PWD} --output "type=oci" > output.tar
error: failed to parse input: proto: illegal wireType 6
```

I have tried different buildkit outputs but all of them have the same line of error. I am quite new to buildkit and buildctl so I am not sure if I am using them wrong. Also not sure if this is question better asked in the pun issues board.

Here are the details of my environment:
| Application | Version Details                                                                     |
|-------------|-------------------------------------------------------------------------------------|
| buildkitd   | buildkitd github.com/moby/buildkit v0.17.0 fd61877fa73693dcd4ef64c538f894ec216409a3 |
| buildctl    | buildctl github.com/moby/buildkit v0.17.0 fd61877fa73693dcd4ef64c538f894ec216409a3  |
| pun         | https://github.com/nubificus/pun/tree/e661806a7b2fc35a7e9117a991728fc6acda4bef      |
| docker      | 27.3.1                                                                              |

**Comment by cmainas** [comment]
Hello @alanpjohn 

it seems the README in `pun` was not up-to-date. We have changed the default behavior to be a buildkit frontend and not printing a LLB. As a result, the buildctl command in the README was not correct. It is still possible to print the LLB with `pun` but we need to use the `--LLB` argument. We have updated the README of the repo.

As such, I was able to build the `http-cpp` example following your steps. In particular:
1. Cloned unikraft's catalog repository `git clone https://github.com/unikraft/catalog.git`
2. Go to `http-cpp` example `cd catalog/examples/http-cpp/`
3. Build it with kraft `kraft build --no-cache --no-update --plat qemu --arch x86_64`
4. Create the following Containerfile
```
#syntax=harbor.nbfc.io/nubificus/urunc/pun/llb:latest
FROM unikraft.org/base:latest

COPY ./.unikraft/build/initramfs-x86_64.cpio /unikernel/initramfs-x86_64.cpio

LABEL com.urunc.unikernel.binary="/unikraft/bin/kernel"
LABEL "com.urunc.unikernel.cmdline"="/http_server"
LABEL "com.urunc.unikernel.initrd"="/unikernel/initramfs-x86_64.cpio"
LABEL "com.urunc.unikernel.unikernelType"="unikraft"
LABEL "com.urunc.unikernel.unikernelVersion"="0.17.0"
LABEL "com.urunc.unikernel.hypervisor"="qemu"
```
5. Build it with `docker build -f Containerfile_http_cpp -t harbor.nbfc.io/nubificus/urunc/http-cpp-unikraft-qemu:build .` or
```
./pun -LLB -f Containerfile_http_cpp | sudo buildctl --addr docker-container://buildkitd build ... --local context=${PWD} --output type=docker,name=harbor.nbfc.io/nubificus/urunc/http-cpp-unikraft-qemu:buildctl | sudo docker load
```
6. Run it with `sudo docker run --rm -it --runtime io.containerd.urunc.v2 harbor.nbfc.io/nubificus/urunc/http-cpp-unikraft-qemu:build`

Output:
```
SeaBIOS (version 1.13.0-1ubuntu1.1)


iPXE (http://ipxe.org) 00:02.0 C000 PCI2.10 PnP PMM+0FF8C820+0FECC820 C000
                                               


Booting from ROM..1: Set IPv4 address 10.4.0.47 mask 255.255.255.0 gw 10.4.0.1
en1: Added
en1: Interface is up
Powered by Unikraft Calypso (0.17.0~62132e5)
Listening on port 8080

```

Some notes:
- In the cmdline annotation, you need to use `/`, otherwise unikraft's elfloader was not able to find the binary
- Since https://github.com/nubificus/urunc/pull/72 is merged, you can directly use `/http_server` as cmdline.
- I was running the buildkit in a docker container, hence I had to pass the address in the builctl command. I run buildkit with `docker run -d --name buildkitd --privileged moby/buildkit:latest`

**Comment by alanpjohn** [comment]
Hi @cmainas 

This was helpful; thank you so much. I was able to fix, build and deploy on urunc. You can go ahead and close this issue.

**Comment by cmainas** [comment]
Hello @alanpjohn ,

we are glad that you were able to fix any issues and even deploy them in `urunc`. I will close the issue as you suggest. Feel free to open it again if a similar issue arises.
