### ISSUE TITLE
Extract target CPU architecture from unikernel binary 

### ISSUE THREAD

**Issue by gntouts** [nubificus/bima#7]
Currently, we rely on a non-standard ARCH instruction provided by the user to determine the CPU architecture for the container image.

This could be extracted by reading the ELF header of the unikernel binary, using [GetBinaryArchitecture()](https://github.com/nubificus/bima/blob/20249e2aa5333d57e12278141828361fdd832119/internal/utils/utils.go#L103).

To do that, we should iterate over every COPY instruction and find the one that matches the file defined from `com.urunc.unikernel.binary` LABEL.

**Comment by cmainas** [comment]
It seems bima expects the binary to be in ELF format, which is not always the case (see Unikraft on aarch64, as pointed by @ananos ). As a result, we should first determine the type of the executable file and then according to its format extract the CPU arch. In order to get the format of the binary we can use the [filetype package](https://pkg.go.dev/github.com/h2non/filetype#section-readme). Then, we need to find a way to read Portable Executable (PE) format files to extract the CPU arch for the binary. I will have soon an implementation.
